[package]
name = "day17"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]
grid = "0.13.0"
pathfinding = "4.8.0"
